### ISSUE TITLE
Secure and HttpOnly cookie

### ISSUE THREAD

**Issue by PericlesTheo** [jameschambers/boring-bits-nextjs#1]
Hey @jameschambers, I found myself reading through the `boring-bits-*` repos 👌 

One question for you: I see when [storing the JWT](https://github.com/jameschambers/boring-bits-nextjs/blob/265a91a1e4ca2d83adf2360f3c34640f36ff54ec/services/TokenService.js#L7) in the cookies, you are not [restricting access to the cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies).

According to the [universal-cookie](https://www.npmjs.com/package/universal-cookie) library they can be set as
```javascript
cookies.set("token", token, {path: "/" ,  secure: true, httpOnly: true})
```

I had a quick glance over the `universal-cookie` library and I don't think they are set by default.

I was wondering if there is a particular reason for omitting the options above 😃

**Comment by jameschambers** [comment]
Hi @PericlesTheo  - thank you for the kind words. 

There's not a specific reason for this, and your more secure option looks like the way to go!
